"""empty message

Revision ID: 9bc45fd3cd55
Revises: 271f0af74088
Create Date: 2021-06-05 16:40:19.913490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc45fd3cd55'
down_revision = '271f0af74088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('book_id', sa.Integer(), nullable=True))
    op.drop_column('cart', 'id_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('id_product', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cart', 'book_id')
    # ### end Alembic commands ###
